global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "auth-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["auth-service:8090"]


  - job_name: "user-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["user-service:8091"]


  - job_name: "vote-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["vote-service:8094"]


  - job_name: "post-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["post-service:8092"]