name: RedditApp CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:

    runs-on: ubuntu-latest

    steps:

      # 1. Get code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Setup Java
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # 3. Build All Services
      - name: Build with Maven
        run: mvn clean package -DskipTests

      # 4. Login to DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 5. Build & Push API Gateway
      - name: Build & Push API Gateway
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/api-gateway ./api-gateway
          docker push ${{ secrets.DOCKER_USERNAME }}/api-gateway

      # 6. Build & Push Auth Service
      - name: Build & Push Auth Service
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/auth-service ./auth-service
          docker push ${{ secrets.DOCKER_USERNAME }}/auth-service
