name: RedditApp CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push API Gateway
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/api-gateway -f api-gateway/Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/api-gateway


      - name: Build & Push Auth Service
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/auth-service -f auth-service/Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/auth-service

      - name: Build & Push user Service
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/user-service -f user-service/Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/user-service
      

      - name: Build & Push post Service
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/post-service -f post-service/Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/post-service
          

      - name: Build & Push feed Service
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/feed-service -f feed-service/Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/feed-service

      - name: Build & Push vote Service
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/vote-service -f vote-service/Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/vote-service


      - name: Build & Push notification Service
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/notification-service -f notification-service/Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/notification-service
          

      - name: Build & Push comment Service
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/comment-service -f comment-service/Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/comment-service

      - name: Build & Push karma Service
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/karma-service -f karma-service/Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/karma-service

      - name: Build & Push discovery-server
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/discovery-server -f discovery-server/Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/discovery-server